---
title: "Leaflet Project"
author: "John Nguyen"
date: "1/3/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(leaflet)
```

## 5 Fun Places to Visit in Ohio On 1/3/2021

```{r, echo = FALSE}
latitude<-c(41.6240560020467,	41.5070817472448,	39.3642414783608,	39.4269931100937,	40.165122629557)
longitude<-c(-81.6027990951782,	-82.6890826592413,	-84.2679544709003,	-82.5286853659996,	-83.1184332355066)

funOhioLocation<-data.frame(latitude,longitude)
sites<-c(
    "<a href='https://www.clevelandart.org/'>Cleveland Art Museum</a>",
    "<a href='https://www.cedarpoint.com/'>Cedar Point</a>",
    "<a href='https://www.visitkingsisland.com/'>Kings Island</a>",
    "<a href='https://www.hockinghills.com/index.html'>Hocking Hills</a>",
    "<a href='https://www.columbuszoo.org/'>Columbus Zoo</a>"
)
funOhioLocation%>%
    leaflet()%>%
    addTiles()%>%
    addMarkers(popup = sites)
```

## Thank you

